DAT-71390 - app components add props to grid component
datorama/app-components pull request #208
Opened 2020-11-16 12:04 UTC by etrubek

## Description
- implement controll columns width.
- add isResizable prop to control the resizable feature.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Are you adding a new package?
- [ ] yes
- [x] no

2020-11-16 13:23 UTC, crazypixel requested changes
do width per header - not one for all. thanks

2020-11-16 13:23 UTC, crazypixel commented on src/components/Grid/Grid.tsx
> +  width?: number;
the width is per header so should be in the header object - 
headers={[ { ... label: '', dataKey: '', width: 300 } ]}

2020-11-16 13:23 UTC, crazypixel commented on src/components/Grid/Grid.tsx
> +  width?: number;
and it's not required.

2020-11-17 07:35 UTC, crazypixel approved these changes

2020-11-17 07:35 UTC, crazypixel commented
/cr-review

2020-11-17 07:39 UTC, Chikel requested changes

2020-11-17 07:39 UTC, Chikel commented on src/components/Grid/Body.tsx
> +      {headers.map((header, i) => {
Let's memoize headers rendering.

2020-11-17 07:39 UTC, Chikel commented on src/components/Grid/Body.tsx
> +  width?: number;
I guess this should be part of `Header` type.

2020-11-17 07:39 UTC, Chikel commented on src/components/Grid/Grid.tsx
> +  isResizable: true,
I'd go with turning all `is...` props to `false`.
This way we have a slim component that you can "turn on" piece by piece.
It might require a short update in the app's story book and in the app.

2020-11-17 07:39 UTC, Chikel commented on src/components/Grid/Header/Header.tsx
> +        }}
I don't see any changes here, let's revert.

2020-11-17 07:39 UTC, Chikel commented on src/components/Grid/Header/Header.tsx
> +      {headers.map((header, i) => {
Let's memoize this as well (i.e a `const renderHeaders = useMemo(headers) => { ... })`).

2020-11-17 09:07 UTC, Chikel approved these changes

2020-11-17 09:32 UTC, merged