DAT-82407 range type input
datorama/app-components pull request #285
Opened 2021-06-06 07:55 UTC by mlevi1806

## Description
Now we can control range component with input
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Are you adding a new package?
- [ ] yes
- [x] no

2021-06-07 10:27 UTC, Chikel requested changes

2021-06-07 10:27 UTC, Chikel commented on src/components/Range/index.tsx
> +/* eslint react/prop-types: 0 */
I see it's switched to TS, that's great!
Can you indicate what lines were changed?

2021-06-07 11:04 UTC, mlevi1806 commented on src/components/Range/index.tsx
> +/* eslint react/prop-types: 0 */
Sure.

Not sure about the lines, but in general, using interface instead of propTypes, which is a known set of props exposed to the consumer.
Moreover, took off all logic into a separated hook.

2021-06-07 11:31 UTC, Chikel commented on src/components/Range/range.hooks.ts
> +      console.log(translateX);
Not sure it's related to your change but let's remove this log.

2021-06-08 07:55 UTC, Chikel approved these changes

2021-06-08 09:14 UTC, mlevi1806 commented
/cr-review

2021-06-08 09:19 UTC, merged