W-10224258 - Add data card component
datorama/app-components pull request #328
Opened 2021-11-24 07:39 UTC by TidharPeer

## Description
Write here a short description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Are you adding a new package?
- [ ] yes
- [x] no

![image](https://user-images.githubusercontent.com/5902007/143195221-f7170024-7834-41ce-9151-feb6e6eb1f54.png)

2021-11-25 06:31 UTC, kaufguy commented on src/components/DataCard.js
> +import { ReactComponent as ChevronUpDoubleAsset } from '../assets/chevron-up-double.svg';
pleaes use absolute path

2021-11-25 06:35 UTC, kaufguy commented on src/components/DataCard.js
> +      box-shadow: 0px 0px 8px rgba(79, 80, 83, 0.15);
theme?

2021-11-25 06:35 UTC, kaufguy commented on src/components/DataCard.js
> +  border: 1px solid rgba(0, 105, 126, 0.15);
theme?

2021-11-25 06:40 UTC, kaufguy commented on src/components/DataCard.js
> +        onClick={() => setSelected(!selected)}
I dont think the click should be on the container but on the checkbox.
Also, I think onClick should be a property that is controlled from the outside (and will modify the checked prop that comes from outside). No need for selected state (its just the 'checked' prop)

2021-11-25 07:21 UTC, TidharPeer commented on src/components/DataCard.js
> +import { ReactComponent as ChevronUpDoubleAsset } from '../assets/chevron-up-double.svg';
Changed to this:
![image](https://user-images.githubusercontent.com/5902007/143397149-923c4582-0e13-4a48-b535-1cbe05a8869b.png)

2021-11-25 08:55 UTC, TidharPeer commented on src/components/DataCard.js
> +        onClick={() => setSelected(!selected)}
Done

2021-11-28 08:55 UTC, distroysf commented on src/components/DataCard.js
> +                  width={'8px'}
put the width in ChevronUpDoubleAsset styled component

2021-11-28 08:56 UTC, distroysf commented on src/components/DataCard.js
> +        className={`card-container ${props.checked ? 'selected' : ''}`}
no need for classes for every component

2021-11-28 09:02 UTC, distroysf approved these changes

2021-11-28 09:54 UTC, distroysf requested changes
remove use of classNames

2021-11-28 11:44 UTC, distroysf commented on src/components/DataCard.js
> +            <IconContainer background={props.iconBackground}>
background prop is not used

2021-11-28 11:47 UTC, distroysf commented on src/components/DataCard.js
> +        <MoreContainer height={props.height} borderColor={props.borderColor}>
remove all style attrs from html

2021-11-28 12:01 UTC, distroysf commented on src/components/DataCard.js
> +                <Label>{props.lessLabel || 'Less'}</Label>
for hardcoded strings use `useTranslations`

2021-11-28 12:02 UTC, distroysf commented on src/components/DataCard.js
> +              {React.cloneElement(props.moreChildren)}
how it's used moreChildren

2021-11-28 12:02 UTC, distroysf commented on src/components/DataCard.js
> +        <Checkbox className={'card-checkbox'} checked={props.checked} />
remove className={'card-checkbox'}

2021-11-28 12:10 UTC, TidharPeer commented on src/components/DataCard.js
> +              {React.cloneElement(props.moreChildren)}
Its the component that being rendered inside the More, if its open

2021-11-28 12:11 UTC, TidharPeer commented on src/components/DataCard.js
> +                <Label>{props.lessLabel || 'Less'}</Label>
Didn't see a single use for it in the app components... this is why I added the props, so users can add their translations

2021-11-28 12:13 UTC, distroysf commented on src/components/DataCard.js
> +                <Label>{props.lessLabel || 'Less'}</Label>
you're correct

2021-11-28 12:24 UTC, distroysf requested changes

2021-11-28 12:24 UTC, distroysf commented on src/components/DataCard.js
> +    <Container className={`${props.className ? props.className : ''}`}>
remove class

2021-11-28 12:24 UTC, distroysf commented on src/components/DataCard.js
> +  ${({ height }) =>
there isn't height prop

2021-11-28 12:29 UTC, distroysf commented on src/components/DataCard.js
> +  margin-left: 7px;
remove all custom margins
this won't grow well in different sizes

2021-11-28 13:31 UTC, distroysf approved these changes

2021-12-07 10:01 UTC, kaufguy approved these changes

2021-12-07 10:23 UTC, merged